export const colors = {
  primary: '#1C3A2F',
  gold: '#C9962A',
  background: '#1C3A2F',
  surface: '#F0F0F0',
  card: '#FFFFFF',
  subtitle: '#A8C5B5',
  textDark: '#1C3A2F',
  textBody: '#666',
  textLight: '#999',
  textInput: '#333',
};

export const commonStyles = {
  header: {
    backgroundColor: '#1C3A2F',
    paddingTop: 56,
    paddingBottom: 32,
    paddingHorizontal: 28,
    alignItems: 'center',
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoTask: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  logoLink: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#C9962A',
  },
  headerSubtitle: {
    color: '#A8C5B5',
    fontSize: 14,
    marginTop: 6,
  },
  divider: {
    width: 48,
    height: 3,
    backgroundColor: '#C9962A',
    borderRadius: 2,
    alignSelf: 'center',
    marginVertical: 12,
  },
  card: {
    backgroundColor: '#F0F0F0',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    flex: 1,
    padding: 24,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#C9962A',
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: '#333',
    marginBottom: 14,
  },
  btnPrimary: {
    backgroundColor: '#C9962A',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  btnPrimaryText: {
    color: '#1C3A2F',
    fontWeight: 'bold',
    fontSize: 16,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#C9962A',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 12,
    marginTop: 20,
  },
  contentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
};